### ISSUE TITLE
Can't compile on Linux with glibc 2.32 (sys_siglist deprecated)

### ISSUE THREAD

**Issue by kitchen-ace** [coelckers/prboom-plus#128]
Quoting from the glibc 2.32 [changelog](https://sourceware.org/pipermail/libc-announce/2020/000029.html):

    The deprecated arrays sys_siglist, _sys_siglist, and sys_sigabbrev
    are no longer available to newly linked binaries, and their declarations
    have been removed from <string.h>.  They are exported solely as
    compatibility symbols to support old binaries.  All programs should use
    strsignal instead.

I assume because the symbol still exists, `check_symbol_exists(sys_siglist "signal.h" HAVE_DECL_SYS_SIGLIST)` in CMakeLists.txt is returning true, resulting in a compilation error.

    src/prboom-plus/prboom2/src/POSIX/i_system.c:129:14: error: ‘sys_siglist’ undeclared (first use in this function)
      129 |   if (strlen(sys_siglist[signum]) < sz)

Temp workaround for anyone trying to compile is to change `#ifdef HAVE_DECL_SYS_SIGLIST` in src/POSIX/i_system.c and src/SDL/i_system.c to `#if 0`

**Comment by kitchen-ace** [comment]
I guess a better workaround is to add `-DHAVE_DECL_SYS_SIGLIST=0` to `cmake ..`

**Comment by fabiangreffrath** [comment]
I guess we should just remove the code using sys_siglist alltogether and use the fallback code instead.
