### ISSUE TITLE
BUILD_GL does not toggle all OpenGL code

### ISSUE THREAD

**Issue by vilhelmgray** [coelckers/prboom-plus#382]
Attempting to building prboom-plus version 2.6.1um with `-DBUILD_GL=no` results in the following error:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: src/CMakeFiles/prboom-plus.dir/d_main.c.o: in function `D_Display':
/tmp/portage/games-fps/prboom-plus-2.6.1/work/prboom-plus-2.6.1um/prboom2/src/d_main.c:399: undefined reference to `gld_ProcessExtraAlpha'
collect2: error: ld returned 1 exit status
```

It looks like this line of code is missing the `GL_DOOM` preprocessor define guard. prboom-plus version 2.6um doesn't seem affected, and it looks this regression was introduced by commit 87fef9d.

**Comment by fabiangreffrath** [comment]
Could you plase file a PR? Thank you!

**Comment by vilhelmgray** [comment]
No problem, I'll write up a patch and open a PR for this probably this weekend. :+1:
